### ISSUE TITLE
Regarding Project Ozone (I don't really have any means of contacting you)

### ISSUE THREAD

**Issue by Sunconure11** [synthetixa/Synthetique#2]
I compiled a list of mods you could possibly use for when you actually build that mod, assuming you will be able to tackle it. Once you see this, save this note somewhere safe, and close this issue. Also, if needed, you could call on me for textures and models if you need any done that you cannot do, assuming you add any new items. However, that might not be for a bit, as I am busy with texturing and modelling for the next GC Module. I also need to help host an ARK server for someone later today (5/2/2016)

A bit of advice though. Reika's mods might not be suited for the bridge, due to how he views changes to his mods.

> For Synthetica:
> 
> A list of various tech, agriculture, and some other miscellaneous mods that could benefit from the bridge. Feel free to add or remove new mods to the list.
> 
> Agricultural (also includes mob-adding mods):
> Harvestcraft
> Harvest The Nether
> Growthcraft CE
> Apple Milk Tea 2
> Lycanites Mobs
> Mo' Creatures
> Plant Mega Pack
> Natura
> Hunger Overhaul
> Psychedelicraft
> The Vegan Option
> 
> Tech:
> Thermal anything
> EnderIO
> Galacticraft
> Forestry (also classifies as agricultural)
> Railcraft
> Mekanism
> Big Reactors
> NuclearCraft
> IC2
> ICBM
> Extra Utilities
> DefenseTech
> Factorization
> Fossils and Archaeology (revival of long-dead animals could have unexpected effects on the environment, however, you might want to construct some kind of food web and a functional ecosystem, since MC does not really have one)
> Tinkers Construct
> 
> Magic:
> Thaumcraft (it sortof has a pollution system already)
> Botania (if anything, using botania might be better for the environment)
> 
> Environmental:
> Highlands
> Enhanced Biomes
> ExtraBiomesXL
> Biomes O' Plenty
> Coro's Weather Mod
> Dynamic Surroundings
> Stellar Sky (smog and pollution could blot out the sky at both day and night if it is bad enough, reducing visibility of celestial bodies)

**Comment by synthetixa** [comment]
Thank you for the ideas. Currently, I've stopped development of Ozone in favor of Synthetique, my main mod. However, when I get Synthetique to a more release-like state, I plan to get back to Ozone. Thank you for the list. I didn't think about all of those and will implement to my best ability when the time comes. For now, I'm sticking with one mod in order to get things done and keep myself sane-ish. If you want, you may pick up Ozone and I will contribute. If that isn't viable, I will definitely get to it eventually. 

Anyway, you could take a look at Synthetique, if you want. I hope that I can simplify modular synthesizers enough to make it plausible. I've got my oscillators making a pitch-adjustable sound which is nice. 

Thanks again for the list. I'll save it and delete this when I get home.
